apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.type: nodeport
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: dynamodb
  name: dynamodb
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: dynamodb
  type: NodePort
status:
  loadBalancer: {}
