apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.service.type: nodeport
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: dynamodb
  name: dynamodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dynamodb
    spec:
      containers:
      - args:
        - -jar
        - DynamoDBLocal.jar
        - -sharedDb
        - -dbPath
        - /home/dynamodblocal/data/
        image: farrion/dynamodb_base:latest
        name: dynamodb
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
