apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o templates
    kompose.service.type: nodeport
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: license-insights
  name: license-insights
spec:
  ports:
  - name: "6162"
    port: 6162
    targetPort: 6162
  selector:
    io.kompose.service: license-insights
  type: NodePort
status:
  loadBalancer: {}
